# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

[default.extend-words]
Ded = "Ded"

[files]
extend-exclude = [
  "go.mod",
]
