# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

# SPDX-FileCopyrightText: 2025 SAP SE
#
# SPDX-License-Identifier: Apache-2.0

[default.extend-words]
# Don't correct ANDed from k8s machinery
Ded = "Ded"

[files]
extend-exclude = [
  "go.mod",
  "vendor/",
]
