# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
#
# SPDX-License-Identifier: Apache-2.0

name: Close inactive issues
on:
  schedule:
    - cron: "36 1 * * *"

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    uses: cloudoperators/common/.github/workflows/shared-stale.yaml@main
